blank_issues_enabled: false
contact_links:
  - name: TF Provider Questions
    url: https://github.com/MNThomson/terraform-provider-dominos/discussions
    about: GitHub issues in this repository are only intended for bug reports and feature requests. Other issues will be closed. Please ask and answer questions through Github Discussions.
