// AUTOGENERATED: DO NOT EDIT
// Update this file from the /tools folder

package provider


import (
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
)

// TODO: Implement https://github.com/hashicorp/terraform-plugin-framework-validators
var optionsAttributes = tfsdk.SingleNestedAttributes(map[string]tfsdk.Attribute{
	"cheese": {
		Description: "",
		Optional:    true,
		Attributes:  itemOptionsAttributes,
	},
	"sauce": {
		Description: "",
		Optional:    true,
		Attributes:  itemOptionsAttributes,
	},
})

type PizzaOptions struct {
	Cheese Option `json:"C"`

	// Pizza Sauces
	PizzaSauce          Option `json:"X,omitempty"`
	BBQSauce            Option `json:"Q,omitempty"`
	AlfredoSauce        Option `json:"Xf,omitempty"`
	HeartyMarinaraSauce Option `json:"Xm,omitempty"`
	RanchDressing       Option `json:"Rd,omitempty"`
	GarlicParmesanSauce Option `json:"Xw,omitempty"`

	// Meats
	Bacon             Option `json:"K,omitempty"`
	BeefCrumble       Option `json:"B,omitempty"`
	BrooklynPepperoni Option `json:"Xp,omitempty"`
	Chicken           Option `json:"D,omitempty"`
	Ham               Option `json:"H,omitempty"`
	Pepperoni         Option `json:"P,omitempty"`
	PhillySteak       Option `json:"St,omitempty"`
	Salami            Option `json:"L,omitempty"`
	Sausage           Option `json:"S,omitempty"`

	// Non-meats
	BabySpinach       Option `json:"Sp,omitempty"`
	BlackOlives       Option `json:"R,omitempty"`
	Cheddar           Option `json:"E,omitempty"`
	Feta              Option `json:"Fe,omitempty"`
	GreenOlives       Option `json:"V,omitempty"`
	GreenPepper       Option `json:"G,omitempty"`
	HotBananaPeppers  Option `json:"Z,omitempty"`
	JalapenoPeppers   Option `json:"J,omitempty"`
	Mushroom          Option `json:"M,omitempty"`
	Onion             Option `json:"O,omitempty"`
	ParmesanAsiago    Option `json:"Pa,omitempty"`
	Pineapple         Option `json:"N,omitempty"`
	Provolone         Option `json:"Cp,omitempty"`
	RoastedRedPeppers Option `json:"Rp,omitempty"`
	Tomatoes          Option `json:"T,omitempty"`
}
