name: Docs

on:
  push:
    branches:
      - master
  pull_request:

env:
  IsPR: "no"

jobs:
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Check if PR
        run: |
          echo "IsPR='yes'" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'
      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@master
        with:
          config-file: ".github/mlc_config.json"
          check-modified-files-only: no
