name: Docs

on:
  push:
    branches:
      - master
  pull_request:

env:
  IsPR: "no"

jobs:
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if PR
        if: github.event_name == 'pull_request'
        run: |
          echo "IsPR='yes'" >> $GITHUB_ENV

      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          config-file: ".github/mlc_config.json"
          check-modified-files-only: ${{ env.IsPR }}
