name: "Misc"

on:
  push:
    branches:
      - master
  pull_request:

jobs: 
  labeler:
    name: PR Labeler
    permissions: 
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps: 
      - uses: actions/labeler@v4
        with: 
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
